TaskDevs/yeshub-template-new

.env, package-lock.json, public/assets/css/style.css, src/App.js, src/app/common/popups/popup-signin.jsx, src/app/common/popups/popup-signup.jsx, src/app/context/auth/AuthContext.jsx, src/app/context/auth/useAuth.jsx, src/app/form-processing/login.jsx, src/app/pannels/public-user/components/pages/after-login.jsx, src/app/pannels/public-user/components/pages/login.jsx
I was having challenges with CORS  and CSRF token so I couldn't register.
=> fix: implemented user authentication

d, src/app/common/popups/popup-portfolio.jsx, src/app/common/portfolio-form.jsx, src/app/common/portfolio-media-form.jsx, src/app/context/category/categoryContextApi.jsx, src/app/context/portfolio/portfolioApi.jsx, src/app/context/portfolio/portfolioContextApi.jsx, src/app/pannels/candidate/components/can-dashboard.jsx, src/app/pannels/candidate/components/can-saved-jobs.jsx, src/app/pannels/candidate/sections/common/can-sidebar.jsx, src/app/pannels/candidate/sections/dashboard/section-can-overview.jsx, src/app/pannels/candidate/sections/resume/section-can-education.jsx, src/app/pannels/candidate/sections/resume/section-can-work-sample.jsx, src/app/pannels/public-user/components/jobs/job-detail1.jsx, src/app/pannels/public-user/sections/jobs/job-card.jsx
I just made an upload for the employers update and saved jobs
=> Update on employers and saved jobs

src/app/pannels/public-user/sections/jobs/sidebar/section-jobs-sidebar2.jsx
Fixed the banner and logo not showing on job detail
=> run up sidebar

src/app/context/user-profile/profileContextApi.jsx, src/app/pannels/public-user/sections/find-talent/ClientFindTalent.jsx
=> find talent

src/app/pannels/public-user/sections/profile/client-profile-forms.jsx, src/app/pannels/public-user/sections/proposals/data.js, src/app/pannels/public-user/sections/proposals/proposal-card.jsx
=> Fixing dashboard update

src/app/pannels/candidate/sections/new-profile/ProfileSection.jsx, src/app/pannels/candidate/sections/new-profile/ProfileSectionsManager.jsx, src/app/pannels/candidate/sections/new-profile/profile-details-components.jsx
The freelance work profile history has been updated. the bio for the profile has also been formatted.
=> freelance work history updated

src/app/context/employers/employerApi.jsx, src/app/context/employers/employerContextApi.jsx, src/app/pannels/public-user/sections/proposals/proposal-card.jsx, src/app/pannels/public-user/sections/proposals/proposal-forms.jsx, src/app/pannels/public-user/sections/proposals/proposal-type-badge.jsx, src/app/pannels/public-user/sections/proposals/proposals.jsx
Proposal view feature integrated
=> New Proposal Features

src/app/pannels/candidate/sections/deliver-work/active-contracts.jsx, src/app/pannels/candidate/sections/deliver-work/submit-form.jsx, src/app/pannels/candidate/sections/deliver-work/submit-proposal.jsx, src/app/pannels/candidate/sections/find-work/find-work-details-new.jsx, src/globals/route-names.jsx, src/routing/candidate-routes.jsx
=> Submit Proposal

src/app/context/payment/paymentApi.jsx, src/app/context/payment/paymentContextApi.jsx, src/app/pannels/candidate/sections/finances/billings-dashboard.jsx, src/app/pannels/candidate/sections/finances/invoice-details.jsx
Fixing client invoices and billings and earnings
=> Client Invoice And Billing and Earnings

src/app/context/payment/paymentApi.jsx, src/app/context/payment/paymentContextApi.jsx, src/app/pannels/candidate/sections/finances/invoice-details.jsx, src/app/pannels/candidate/sections/finances/invoice.jsx
=> Invoice CRUD completed

src/App.jsx, src/app/context/freelance/freelanceApi.jsx, src/app/context/freelance/freelanceContextApi.jsx, src/app/context/payment/paymentContextApi.jsx, src/app/context/transaction/transactionApi.jsx, src/app/context/transaction/transactionContextApi.jsx, src/app/pannels/candidate/sections/finances/billings-dashboard.jsx, src/app/pannels/candidate/sections/finances/finance-dashboad.jsx, src/app/pannels/candidate/sections/finances/transactions.jsx, src/app/pannels/public-user/sections/find-talent/new-find-talent.jsx, src/utils/truncateText.jsx
=> Financial overview done

src/app/pannels/candidate/sections/deliver-work/submit-form.jsx
=> Submit work with routing done

src/app/context/task/taskContextApi.jsx, src/app/pannels/candidate/components/can-dashboard.jsx, src/app/pannels/candidate/sections/deliver-work/active-contracts.jsx, src/app/pannels/candidate/sections/deliver-work/contracts-history.jsx, src/app/pannels/candidate/sections/deliver-work/submit-form.jsx
Contracts history and activity done
=> Contract History and Activity done

src/app/context/employers/employerApi.jsx, src/app/context/employers/employerContextApi.jsx, src/app/pannels/employer/components/applicant/interview-modal.jsx, src/app/pannels/employer/components/applicant/job-applicant.jsx, src/app/pannels/employer/components/jobs/manage-projects.jsx, src/app/pannels/employer/components/project/create-project.jsx, src/app/pannels/employer/components/talent-pool/talent-pool.jsx, src/app/pannels/public-user/sections/dashboard/client-dashboard.jsx, src/app/pannels/public-user/sections/dashboard/client-hiring-quick-actions.jsx, src/app/pannels/public-user/sections/find-talent/TalentCard.jsx, src/app/pannels/public-user/sections/find-talent/freelancer-details-two.jsx, src/app/pannels/public-user/sections/profile/client-profile-forms.jsx, src/globals/route-names.jsx, src/routing/client-routes.jsx
Creating and managing job applications
=> Create and Manage job application

src/app/context/employers/employerApi.jsx, src/app/context/employers/employerContextApi.jsx, src/app/pannels/employer/components/applicant/interview-modal.jsx, src/app/pannels/employer/components/applicant/job-applicant.jsx, src/app/pannels/employer/components/jobs/manage-jobs.jsx, src/app/pannels/employer/components/project/create-project.jsx, src/app/pannels/employer/components/project/preview-modal.jsx
Creating Project Partially done
=> Create Project Partially Done

src/app/common/header/new-header.jsx, src/app/context/employers/employerApi.jsx, src/app/context/employers/employerContextApi.jsx, src/app/context/jobs/jobsContextApi.jsx, src/app/pannels/candidate/sections/find-work/find-work-page.jsx, src/app/pannels/employer/components/jobs/manage-projects.jsx, src/app/pannels/employer/components/project/create-project.jsx, src/app/pannels/employer/components/project/preview-modal.jsx, src/app/pannels/employer/components/why/why.jsx, src/globals/route-names.jsx, src/routing/public-user-routes.jsx
=> Fixing find jobs

src/app/common/header/new-header.jsx, src/app/context/employers/employerApi.jsx, src/app/context/employers/employerContextApi.jsx, src/app/context/freelance/freelanceApi.jsx, src/app/context/freelance/freelanceContextApi.jsx, src/app/pannels/candidate/components/can-active-projects.jsx, src/app/pannels/candidate/components/can-dashboard.jsx, src/app/pannels/employer/components/jobs/manage-projects.jsx, src/app/pannels/employer/components/project/preview-modal.jsx, src/app/pannels/employer/components/talent-pool/add-task-modal.jsx, src/app/pannels/employer/components/talent-pool/freelance-project-manage.jsx, src/app/pannels/employer/components/talent-pool/talent-pool.jsx, src/app/pannels/public-user/sections/dashboard/client-dashboard.jsx, src/globals/constants.jsx, src/globals/route-names.jsx, src/routing/candidate-routes.jsx, src/routing/client-routes.jsx
=> Chat System completed

src/app/common/header/new-header.jsx, src/app/context/employers/employerContextApi.jsx, src/app/context/freelance/freelanceContextApi.jsx, src/app/pannels/employer/components/talent-pool/freelance-project-manage.jsx, src/app/pannels/employer/components/talent-pool/talent-pool.jsx, src/app/pannels/public-user/components/pages/new-auth-form.jsx
=> Fixed Chat bugs

src/app/context/employers/employerApi.jsx, src/app/context/employers/employerContextApi.jsx, src/app/context/jobs/jobsApi.jsx, src/app/context/jobs/jobsContextApi.jsx, src/app/pannels/candidate/sections/find-work/find-work-details-new.jsx, src/app/pannels/employer/components/applicant/SalaryModal.jsx, src/app/pannels/employer/components/applicant/job-applicant.jsx, src/app/pannels/employer/components/jobs/manage-job-details.jsx, src/app/pannels/employer/components/jobs/manage-projects.jsx, src/app/pannels/employer/components/project/create-project.jsx, src/app/pannels/employer/components/talent-pool/add-task-modal.jsx, src/app/pannels/employer/components/talent-pool/freelance-project-manage.jsx, src/app/pannels/employer/components/talent-pool/talent-pool.jsx, src/app/pannels/public-user/components/jobs/new-job-details.jsx, src/routing/candidate-routes.jsx, src/routing/client-routes.jsx, src/utils/dateUtils.jsx
=> Fixing Bugs

src/app/context/employers/employerContextApi.jsx, src/app/pannels/employer/components/talent-pool/freelance-project-manage.jsx, src/app/pannels/employer/components/talent-pool/talent-pool.jsx
Fixing minor bugs and we are good to go
=> Minor bug fixs

src/app/context/employers/employerApi.jsx, src/app/context/employers/employerContextApi.jsx, src/app/pannels/employer/components/jobs/manage-projects.jsx, src/app/pannels/employer/components/project/caution-modal.jsx, src/app/pannels/employer/components/project/create-project.jsx, src/app/pannels/employer/components/project/preview-modal.jsx, src/app/pannels/employer/components/talent-pool/add-milestone-modal.jsx, src/app/pannels/employer/components/talent-pool/add-team-member-modal.jsx, src/app/pannels/employer/components/talent-pool/freelance-project-manage.jsx, src/app/pannels/employer/components/talent-pool/payment-prompt.jsx, src/app/pannels/employer/components/talent-pool/receipt-modal.jsx, src/app/pannels/employer/components/talent-pool/talent-pool.jsx, src/utils/generateRefNo.jsx
Worked on talent pool and create project
=> Fixing talent pool issues

src/app/context/employers/employerContextApi.jsx, src/app/context/transaction/transactionContextApi.jsx, src/app/pannels/candidate/sections/client-finance/financial-overview.jsx
Fixing client finance overview
=> Fixing Client Finance Overview

src/app/context/transaction/transactionApi.jsx, src/app/context/transaction/transactionContextApi.jsx, src/app/pannels/candidate/sections/finances/finance-dashboad.jsx
We are really fixing related data
=> Fixing Transaction Data

src/app/context/proposal/proposalApi.jsx, src/app/context/proposal/proposalContextApi.jsx, src/app/pannels/candidate/sections/deliver-work/submit-form.jsx, src/app/pannels/employer/components/talent-pool/freelance-project-manage.jsx
Fixing minor issues part three
=> Fixing Minor Issues Part Three

src/app/context/transaction/transactionContextApi.jsx, src/app/pannels/candidate/sections/client-finance/financial-overview.jsx, src/app/pannels/employer/components/talent-pool/freelance-project-manage.jsx
We are bringing the deposit button back
=> Bringing the deposit button back

src/app/context/payment/paymentApi.jsx, src/app/context/payment/paymentContextApi.jsx, src/app/context/transaction/transactionApi.jsx, src/app/context/transaction/transactionContextApi.jsx, src/app/pannels/candidate/sections/client-finance/financial-overview.jsx, src/app/pannels/candidate/sections/dashboard/can-recent-activity.jsx, src/app/pannels/candidate/sections/deliver-work/active-contracts.jsx, src/app/pannels/candidate/sections/deliver-work/contracts-history.jsx, src/app/pannels/candidate/sections/deliver-work/submit-form.jsx, src/app/pannels/candidate/sections/deliver-work/submit-work.jsx, src/app/pannels/candidate/sections/finances/billings-dashboard.jsx, src/app/pannels/candidate/sections/finances/finance-dashboad.jsx, src/app/pannels/employer/components/jobs/AddFundsModal.jsx, src/app/pannels/employer/components/jobs/manage-projects.jsx, src/app/pannels/employer/components/project/create-project.jsx, src/app/pannels/employer/components/talent-pool/add-task-modal.jsx, src/app/pannels/employer/components/talent-pool/freelance-project-manage.jsx, src/app/pannels/employer/components/talent-pool/talent-pool.jsx, src/app/pannels/public-user/sections/find-talent/freelancer-details.jsx
We are integrating finance issues
=> Integratinging Finance Issues

src/app/common/header/new-header.jsx, src/app/context/employers/employerContextApi.jsx, src/app/context/transaction/transactionContextApi.jsx, src/app/pannels/candidate/components/can-dashboard.jsx, src/app/pannels/candidate/sections/client-finance/financial-overview.jsx, src/app/pannels/employer/components/applicant/interview-modal.jsx, src/app/pannels/employer/components/talent-pool/talent-pool.jsx, src/app/pannels/public-user/sections/dashboard/client-dashboard.jsx, src/app/pannels/public-user/sections/dashboard/client-overview.jsx
Fixing graph and notifications
=> Fixing Graphs and notifications

src/app/pannels/candidate/sections/deliver-work/active-contracts.jsx, src/app/pannels/candidate/sections/finances/finance-settings.jsx, src/app/pannels/public-user/sections/profile/client-profile.jsx
Fixed client routes and minor issues
=> Fixed Minor Issues

src/app/pannels/public-user/components/jobs/new-job-details.jsx
=> Fixing job details page

src/app/pannels/candidate/sections/client-finance/financial-overview.jsx, src/app/pannels/employer/components/applicant/interview-modal.jsx
=> Fixing Minor Issues

src/app/pannels/candidate/sections/client-finance/financial-overview.jsx, src/app/pannels/candidate/sections/deliver-work/submit-form.jsx, src/app/pannels/candidate/sections/new-profile/profile-components.jsx, src/app/pannels/candidate/sections/offers/offers.jsx, src/app/pannels/employer/components/applicant/job-applicant.jsx, src/app/pannels/employer/components/project/create-project.jsx, src/app/pannels/employer/components/project/preview-modal.jsx, src/app/pannels/employer/components/talent-pool/talent-pool.jsx
Fix Proposal not showing topup redirect and others
=> Minor changes
